# Generated by Django 3.2.21 on 2023-10-03 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroomAssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('assignment_id', models.CharField(max_length=200)),
                ('assignment_title', models.CharField(max_length=200)),
                ('assignment_description', models.TextField(blank=True, null=True)),
                ('assignment_due_date', models.DateTimeField(blank=True, null=True)),
                ('grade', models.FloatField()),
                ('max_points', models.FloatField()),
                ('last_fetch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
