# Generated by Django 3.2.22 on 2023-10-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20231004_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('possible_points', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major_grades', models.ManyToManyField(related_name='major_students', to='student.Grade')),
                ('minor_grades', models.ManyToManyField(related_name='minor_students', to='student.Grade')),
            ],
        ),
    ]
