# Generated by Django 3.2.22 on 2023-10-20 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_course_grade_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignment_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
