# Generated by Django 3.2.21 on 2023-10-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_gradingaverage_gradingperiod_progressreportperiod_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='gradingaverage',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.gradecategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gradingaverage',
            unique_together={('student', 'section', 'category')},
        ),
    ]
